#!/bin/bash

sudo apt install python3-venv -y

# Clean previous builds
rm -rf AppDir build dist venv Meganimus.spec Meganimus*.AppImage

python3 -m venv venv
source venv/bin/activate
pip install pyinstaller PyQt6==6.10.1 PyQt6-Qt6==6.10.1 tomlkit requests

# I'm using Kvantum from lxqt-support-core24 because it's built without KDE dependencies.
pyinstaller --onefile --windowed --name Meganimus \
  --add-binary "/snap/lxqt-support-core24/current/usr/lib/x86_64-linux-gnu/qt6/plugins/iconengines/libQt6XdgIconPlugin.so:PyQt6/Qt6/plugins/iconengines" \
  --add-binary "/snap/lxqt-support-core24/current/usr/lib/x86_64-linux-gnu/qt6/plugins/platformthemes/libqtlxqt.so:PyQt6/Qt6/plugins/platformthemes" \
  --add-binary "/snap/lxqt-support-core24/current/usr/lib/x86_64-linux-gnu/qt6/plugins/styles/libkvantum.so:PyQt6/Qt6/plugins/styles" \
  --add-binary "/snap/lxqt-support-core24/current/usr/lib/x86_64-linux-gnu/lib*:." \
  --add-binary "/snap/kf6-core24/current/usr/lib/x86_64-linux-gnu/qt6/plugins/platformthemes/libqxdgdesktopportal.so:PyQt6/Qt6/plugins/platformthemes" \
  --add-binary "/snap/kf6-core24/current/usr/share/qt6/translations/*:PyQt6/Qt6/translations" \
  meganimus

if ! command -v appimagetool &> /dev/null; then
    echo "Downloading appimagetool..."
    wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool
    chmod +x appimagetool
fi

# Create AppDir structure
mkdir -p AppDir

# Copy Meganimus files
echo "Copying files to AppDir..."

# Copy the Meganimus binary that was generated with PyInstaller.
cp dist/Meganimus AppDir/

# Copy translation folder
cp -r translation AppDir/

# Copy .svg and .desktop files
cp io.github.kyuyrii.meganimus.svg AppDir/
cp io.github.kyuyrii.meganimus.desktop AppDir/

# Copy Meganimus code.
# This isn't important for the AppImage to function; it's just to have easier access to the Meganimus code.
cp meganimus AppDir/

# Create AppRun
cat > AppDir/AppRun << 'EOF'
#!/bin/bash
if [ -z "$APPIMAGE" ]; then
    self="$(readlink -f -- "$0")"
    export APPDIR="${self%/*}"
fi

export QT_QPA_PLATFORMTHEME=xdgdesktopportal

exec "$APPDIR/Meganimus" "$@"
EOF
chmod +x AppDir/AppRun

# Generate AppImage
ARCH=x86_64 ./appimagetool AppDir

echo "AppImage created: $(ls *.AppImage)"
