#!/bin/bash

sudo apt install python3-venv -y

# Clean previous builds
rm -rf AppDir build dist venv Meganimus.spec Meganimus*.AppImage

python3 -m venv venv
source venv/bin/activate
pip install pyinstaller PyQt6==6.10.1 PyQt6-Qt6==6.10.1 tomlkit requests

# I'm using Kvantum from lxqt-support-core24 because it's built without KDE dependencies.
pyinstaller --onefile --windowed --name Meganimus \
  --add-binary "/snap/lxqt-support-core24/current/usr/lib/x86_64-linux-gnu/qt6/plugins/iconengines/libQt6XdgIconPlugin.so:PyQt6/Qt6/plugins/iconengines" \
  --add-binary "/snap/lxqt-support-core24/current/usr/lib/x86_64-linux-gnu/qt6/plugins/platformthemes/libqtlxqt.so:PyQt6/Qt6/plugins/platformthemes" \
  --add-binary "/snap/lxqt-support-core24/current/usr/lib/x86_64-linux-gnu/qt6/plugins/styles/libkvantum.so:PyQt6/Qt6/plugins/styles" \
  --add-binary "/snap/lxqt-support-core24/current/usr/lib/x86_64-linux-gnu/lib*:." \
  --add-binary "/snap/kf6-core24/current/usr/lib/x86_64-linux-gnu/qt6/plugins/platformthemes/libqxdgdesktopportal.so:PyQt6/Qt6/plugins/platformthemes" \
  --add-binary "/snap/kf6-core24/current/usr/share/qt6/translations/*:PyQt6/Qt6/translations" \
  meganimus

if ! command -v appimagetool &> /dev/null; then
    echo "Downloading appimagetool..."
    wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool
    chmod +x appimagetool
fi

# Create AppDir structure
mkdir -p AppDir

# Copy Meganimus files
echo "Copying files to AppDir..."

# Copy the Meganimus binary that was generated with PyInstaller.
cp dist/Meganimus AppDir/

# Copy translation folder
cp -r translation AppDir/

# Copy .svg and .desktop files
cp io.github.kyuyrii.meganimus.svg AppDir/
cp io.github.kyuyrii.meganimus.desktop AppDir/

# Copy Meganimus code.
# This isn't important for the AppImage to function; it's just to have easier access to the Meganimus code.
cp meganimus AppDir/

# Create AppRun
cat > AppDir/AppRun << 'EOF'
#!/bin/bash
if [ -z "$APPIMAGE" ]; then
    self="$(readlink -f -- "$0")"
    export APPDIR="${self%/*}"
fi

export PATH="$APPDIR/bin:$PATH"
export APPIMAGE_EXTRACT_AND_RUN=1
export QT_QPA_PLATFORMTHEME=xdgdesktopportal

mkdir -p "$HOME/.local/share/icons/hicolor/scalable/apps"
mkdir -p "$HOME/.local/share/applications"

# Copy icon if it doesn't exist.

if [ ! -f "$HOME/.local/share/icons/hicolor/scalable/apps/io.github.kyuyrii.meganimus.svg" ]; then
    mkdir -p "$HOME/.local/share/icons/hicolor/scalable/apps"
    cp "$APPDIR/io.github.kyuyrii.meganimus.svg" "$HOME/.local/share/icons/hicolor/scalable/apps/"
fi

# Copy/Update the .desktop file
if [ -f "$HOME/.local/share/applications/io.github.kyuyrii.meganimus.desktop" ]; then
    # If it already exists, update.
    sed -i "s|Exec=.*|Exec=$APPIMAGE|" "$HOME/.local/share/applications/io.github.kyuyrii.meganimus.desktop"
    sed -i "s|Name=.*|Name=Meganimus [AppImage]|" "$HOME/.local/share/applications/io.github.kyuyrii.meganimus.desktop"
else
    # If it doesn't exist, copy and update.
    cp "$APPDIR/io.github.kyuyrii.meganimus.desktop" "$HOME/.local/share/applications/"
    sed -i "s|Exec=.*|Exec=$APPIMAGE|" "$HOME/.local/share/applications/io.github.kyuyrii.meganimus.desktop"
    sed -i "s|Name=.*|Name=Meganimus [AppImage]|" "$HOME/.local/share/applications/io.github.kyuyrii.meganimus.desktop"
    chmod +x "$HOME/.local/share/applications/io.github.kyuyrii.meganimus.desktop"
fi

exec "$APPDIR/Meganimus" "$@"
EOF
chmod +x AppDir/AppRun

# Generate AppImage
ARCH=x86_64 ./appimagetool AppDir

echo "AppImage created: $(ls *.AppImage)"
