[x86_64]
azaharplus_current = "https://github.com/AzaharPlus/AzaharPlus/releases/download/AZAHAR_PLUS_2124_3_A/azaharplus-2124.3-A-linux.zip"
azaharplus_file = "azahar.AppImage"
cemu_current = "https://github.com/cemu-project/Cemu/releases/download/v2.6/Cemu-2.6-x86_64.AppImage"
dolphin_current = "https://github.com/pkgforge-dev/Dolphin-emu-AppImage/releases/download/2512%402026-02-22_1771750440/Dolphin_Emulator-2512-anylinux-x86_64.AppImage"
duckstation_current = "https://github.com/Kyuyrii/Duckstation-GPL3/releases/download/v0.1-7371/DuckStation-x64.AppImage"
eden_current = "https://git.eden-emu.dev/eden-emu/eden/releases/download/v0.2.0-rc1/Eden-Linux-v0.2.0-rc1-legacy-gcc-standard.AppImage"
flycast_current = "https://github.com/flyinghead/flycast/releases/download/v2.6/flycast-x86_64.AppImage"
melonds_current = "https://github.com/melonDS-emu/melonDS/releases/download/1.1/melonDS-1.1-appimage-x86_64.zip"
melonds_file = "melonDS-x86_64.AppImage"
mgba_current = "https://github.com/mgba-emu/mgba/releases/download/0.10.5/mGBA-0.10.5-appimage-x64.appimage"
pcsx2_current = "https://github.com/PCSX2/pcsx2/releases/download/v2.6.3/pcsx2-v2.6.3-linux-appimage-x64-Qt.AppImage"
ppsspp_current = "https://github.com/hrydgard/ppsspp/releases/download/v1.20.2/PPSSPP-v1.20.2-anylinux-x86_64.AppImage"
rmg_current = "https://github.com/Rosalie241/RMG/releases/download/v0.8.9/RMG-Portable-Linux64-v0.8.9.AppImage"
rpcs3_current = "https://github.com/RPCS3/rpcs3-binaries-linux/releases/download/build-71f0d5c60233494e7fe2c3f2ff416a00c87480fb/rpcs3-v0.0.40-18922-71f0d5c6_linux64.AppImage"
ryubing_current = "https://git.ryujinx.app/api/v4/projects/1/packages/generic/Ryubing/1.3.3/ryujinx-1.3.3-x64.AppImage"
snes9x_current = "https://github.com/snes9xgit/snes9x/releases/download/1.63/Snes9x-1.63-x86_64.AppImage"
wine_current = "https://github.com/pkgforge-dev/wine-AppImage/releases/download/11.3-1%402026-03-01_1772357391/wine-11.3-1-anylinux-x86_64.AppImage"
